index.html
Tried to update some things for v0.6 and DataFrames 0.11
=> updates to IO, DataFrames, and little in Matrices

README.md, index.html
=> couple more little tweaks

index.html
https://discourse.julialang.org/t/excellent-cheat-sheet/7792
=> integration comments from discourse, especially in Types section

index.html
Fixed invalid link to julia doc and change julialang.org from http to https.
=> Fixed invalid link to julia doc and change julialang.org from http to https

cheatsheet.css, index.html
=> first pass at 1.0 updates

index.html
changed "Devectorizing" to "Vectorizing"
=> fix typo in performance tips

index.html
hi, thanks for the sharing of the Julia Cheat-Sheet.
=> fix for the NewException with struct

index.html
Fixes  https://github.com/JuliaDocs/Julia-Cheat-Sheet/issues/26
=> Fixes for Conventions, CSV, DataFrames, Arrays, Exceptions

_includes/en/Missing-and-Nothing.md
Hi, your sheet looks great! Proposing a minor formatting change to aid clarity
=> Add clarity with formatting change

_includes/br/Arrays.md, _includes/br/Basics.md
I have translated br/{Array,Basics}.md
=> Some Brazilian translate

_includes/br/Characters-and-strings.md, _includes/en/Characters-and-strings.md
=> Capitalize 8-digit hex

_includes/en/IDEs-Editors-and-Plugins.md, _includes/en/Types.md
Fix issues brought up in https://discourse.julialang.org/t/ann-julia-cheatsheet-updated-for-julia-1-0/15535/11
=> fix IDEs and subtypes

_includes/en/Naming-Conventions.md
=> fix a dead link

_includes/br/Exceptions.md, _includes/br/Functions.md
- Bug fix
- Using `white-space: pre-wrap;` in CSS
ref: #82
=> [br] Bug fix

_includes/zh-cn/Exceptions.md, _includes/zh-cn/Modules.md, _includes/zh-cn/Package-management.md, _includes/zh-cn/Standard-libraries.md
- translated `Exceptions.md` `Package-management.md` `Standard-libraries.md`
- translated part of `Modules.md`
=> [Translation][zh-cn] translated Part3

_includes/zh-cn/Arrays.md, _includes/zh-cn/IO.md, _includes/zh-cn/Linear-Algebra.md
- `dot` has been moved to `LinearAlgebra` in `LinearAlgebra.md`
- update links point to more specific section in `LinearAlgebra.md`
- translated `Arrays.md` `IO.md` `Linear-Algebra.md`
=> [zh-cn] Translation part 6

_includes/en/Missing-and-Nothing.md
skipmissing returns an iterator (more efficient actually)
To create an array from it it needs to be collected
=> Example for skipmissing does not work as is

_includes/br/Sets.md
=> Ajustes finais na tradução de Sets.md

_includes/br/Linear-Algebra.md
Correçoes e ajustes em AlgebraLinear.md
=> Correções na tradução de AlgebraLinear.md

_includes/br/Naming-Conventions.md
Correções e tradução realizadas em Naming-Conventions.md
=> Mais traduções em Naming-Conventions.md

_includes/br/Exceptions.md
=> Tradução finalizada de Exceptions.md

_includes/br/Expressions.md
Finalizando o PR #66 ft @gustavosarturi :smile:
=> Translate expressions pt br

_includes/zh-cn/Characters-and-strings.md
=> [zh-cn] fix typo

_includes/br/The-shell-aka-REPL.md
Added a pt-br translation to The-shell-aka-REPL.md
=> [pt-br] Update br/The-shell-aka-REPL.md

_includes/br/The-shell-aka-REPL.md
Originally proposed in #129 (/cc @paulorasilva)
=> Small fixes to br/The-shell-aka-REPL.md

_includes/br/Noteworthy-packages-and-projects.md, _includes/en/Noteworthy-packages-and-projects.md, _includes/es/Noteworthy-packages-and-projects.md, _includes/fr/Noteworthy-packages-and-projects.md
=> JuliaDiffEq => SciML

_includes/en/What-is.md, _includes/fr/Characters-and-strings.md, _includes/fr/DataFrames.md, _includes/fr/Dictionaries.md, _includes/fr/Expressions.md, _includes/fr/IDEs-Editors-and-Plugins.md, _includes/fr/IO.md, _includes/fr/Introspection-and-reflection.md, _includes/fr/Linear-Algebra.md, _includes/fr/Macros.md, _includes/fr/Missing-and-Nothing.md, _includes/fr/Naming-Conventions.md, _includes/fr/Noteworthy-packages-and-projects.md, _includes/fr/Numbers.md, _includes/fr/Parallel-Computing.md, _includes/fr/Performance-tips.md, _includes/fr/Random-Numbers.md, _includes/fr/Resources.md, _includes/fr/Sets.md, _includes/fr/Videos.md
99% sure about the translation (some concepts do not meet satisfying french word).
Untranslated text might remain (for edits in these commits) as *unmodified* .
=> French translation

_includes/en/Macros.md
https://docs.julialang.org/en/v1/manual/metaprogramming/#Macro-invocation
=> Fix macro usage for en version

_includes/en/IDEs-Editors-and-Plugins.md
did not add for the other languages since I don't know them
=> added maintence mode forb the Juno Ide

_includes/en/Basics.md
I consider this is a cool form to define a function (equation) in Julia.
=> Update Basics.md including Function definition Assignment form

Julia Cheat Sheet Markdown.md
Collated the cheat sheet content into Markdown for people who'd like to copy it over to local notes. Any suggestions for modifications/improvements are welcome.
=> Create Julia Cheat Sheet Markdown.md

Julia Cheat Sheet Markdown.md
Corrected (or at least improved) description for `@which` macro.
=> Update Julia Cheat Sheet Markdown.md
